### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by TeemuKoivisto** [juhohei/shoutr#1]
Ladattu 16.4 klo 22:00

Projekti on hyvin vaikuttava ja javascript näyttää olevan hyvin hallussa. Tämmöisenä vielä keskenkasvuisena fuksina en voi pahemmin kommentoida muuta kuin et hianolt näyttää.

Joten siitä vähästä mitä ymmärsin:

Editti toimii pienellä viiveellä siinä nähden että kun muokkaan viestiä ja haluan vielä sen jälkeen uudelleenmuokata niin vanha viesti näkyy silloin tekstikentässä. Tämä sitten päivittyy kuitenkin aika nopeasti uusimpaan. Aika jännä.

Joku siinä kuitenkin on koska vanhaa dataa tulee tavattua useamminkin. 

Jotain on tosiaan jännästi jossain koska myöskin log outtaus tai log in tai sign up eivät myöskään aina välttämättä toimi.

Tai siis ongelma on että sivut eivät huomaa kun olen logannut sisään ja näyttää yhä log inin ja sign upin vaikka olen jo kirjautunut.

Jaaaa kommenttejen pituutta ei näytä olevan rajoitettu mitenkään.

Sekä kun kommentoi niin sivu ei refreshaannu automaattisesti.
Kuten myös deletointi.

Ylipitkät syötteet näyttävät muutenkin hajottavan kaiken. 

Taisin rikkoa sen. Hups.

Eli näyttää että olen kirjatunut toisella tunnuksella kuin millä juuri postasin. Server kai hiukka hidas.

Enkä oikein tiedä miten tuon searchin pitäisi toimia. En tiiä miksei toimi nyt kun sain kaiken jumiin.

Ja vissiin jos rämpyttää postia kun luo uuden keskustelun voi saada kivasti duplikaatteja. Näköjään kaikki keskustelut myös ovat aina etusivulla jotain se voipi hiukan venyä liikaa jos keskusteluja on paljon.

Ihan jumiin sain sen. En tiiä onko serverin vika mutta sekaisin sen saa. Kenties stabiiliutta voisi vähän parantaa.

Koodista en tajunnut oikein mitään eikä virtuaali ubuntuni oikein osannut asentaa ohjelmaa oikein. Valitti npm installista ja niistä kolmen lisäkirjaston asennuksesta

**Comment by juhohei** [comment]
Kiitos kommenteista. Koitan vastata samassa järjestyksessä kun toit asioita esille:

1. Vanha data löytää tiensä ruutuun Flux-arkkitehtuurissa käytettävistä Storeista, joihin tulee siirrettyä dataa vähän vääristä paikoista ja väärään aikaan. Eli ihan oma moka näin Flux-noviisina. Tarkoitus korjata tämä seuraavaksi.

2. Login/logout/signup-ongelma kuulosta oudolta, en ole itse huomannut vastaavaa. Voitko kertoa tarkemmin, milloin tuo tapahtuu? Session ei pitäisi tällä hetkellä siirtyä välilehdeltä toiselle tai pysyä sivustolta poisnavigoidessa voimassa. Muuten pitäisi toimia, ellei node ole kaatunut välissä ja silloin ongelma olisi käsittääkseni päinvastainen (eli käyttäjätunnus näkyisi ruudulla vaikka ei olisikaan kirjautunut). Node ei käynnistyisi itsekseen uudelleen, joten tilanne on teoreettinen.

3. Kommentoinissa sivu ei päivity, koska kommentti lisätään Storeen ja View päivitetään Storen kautta. Eli kommentoidessa kommentti ilmestyy suoraan kommenttiketjun pohjalle ilman päivitystä. Tätä voisin  selkeyttää. Deletoinnissa sivun pitäisi väliaikaisratkaisuna uudelleenohjautua etusivulle. Itse en ainakaan saa tätä rikottua.

4. Kommenttien ja postauksien pituutta ei ole tosiaan rajoitettu, pitääpä toteuttaa :)

5. Käyttöliittymän searchia ei ole toteutettu (kuten readme kertoo), suoraan APIn kautta se pelittää. Vähän hämäävä se toimimaton hakuboksi kieltämättä.

6. Serveri on kyllä hidas, mutta käyttäjätunnusongelma liittynee joko kohtaan 1 tai 2.

7. Duplikaattionglema pitää korjata :) Etusivun keskustelut on tarkoitus joko ladata laiskasti Facebook-tyyliin tai kylmästi näyttää vain pariky, en ollut testannutkaan sitämmentä uusinta. Hashtag-sivuille sama juttu, kunhan saan ne toteutettua.

8. Ne kolme lisäkirjastoa tarvitsee ainoastaan, jos muuttaa fronttikoodia, ja niiden asentamiseen tarvitsee root-oikeudet. Muuten asennuksen pitäisi sujua sulavasti, sekä 178.62.110.15 (Ubuntu) että läppärini (Arch) ovat asentaneet paketit mukisematta.

**Comment by TeemuKoivisto** [comment]
Eli tuo login/logout/signup ongelma johtui näköjään serverin hetkittäisestä hitaudesta. Eilen illalla kun sitä pommitin monella yhtä aikaisella kirjautumisella varmaan joku pyyntö jäi saapumatta eikä siis huomioinut että olen loggautunut ulos/sisään.
